# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pagesetup.ui'
#
# Created: Tue Sep 29 11:52:53 2009
#      by: PyQt4 UI code generator 4.5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(367, 360)
        self.formLayout = QtGui.QFormLayout(Form)
        self.formLayout.setContentsMargins(0, 0, 0, -1)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(Form)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.firstTemplate = QtGui.QComboBox(Form)
        self.firstTemplate.setObjectName("firstTemplate")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.firstTemplate)
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.size = QtGui.QComboBox(Form)
        self.size.setObjectName("size")
        self.size.addItem(QtCore.QString())
        self.size.addItem(QtCore.QString())
        self.size.addItem(QtCore.QString())
        self.size.addItem(QtCore.QString())
        self.size.addItem(QtCore.QString())
        self.size.addItem(QtCore.QString())
        self.size.addItem(QtCore.QString())
        self.size.addItem(QtCore.QString())
        self.size.addItem(QtCore.QString())
        self.size.addItem(QtCore.QString())
        self.size.addItem(QtCore.QString())
        self.size.addItem(QtCore.QString())
        self.size.addItem(QtCore.QString())
        self.size.addItem(QtCore.QString())
        self.size.addItem(QtCore.QString())
        self.size.addItem(QtCore.QString())
        self.size.addItem(QtCore.QString())
        self.size.addItem(QtCore.QString())
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.size)
        self.label_3 = QtGui.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.height = QtGui.QLineEdit(Form)
        self.height.setObjectName("height")
        self.horizontalLayout_3.addWidget(self.height)
        self.height_unit = QtGui.QComboBox(Form)
        self.height_unit.setObjectName("height_unit")
        self.horizontalLayout_3.addWidget(self.height_unit)
        self.formLayout.setLayout(2, QtGui.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.label_4 = QtGui.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.width = QtGui.QLineEdit(Form)
        self.width.setObjectName("width")
        self.horizontalLayout_4.addWidget(self.width)
        self.width_unit = QtGui.QComboBox(Form)
        self.width_unit.setObjectName("width_unit")
        self.horizontalLayout_4.addWidget(self.width_unit)
        self.formLayout.setLayout(3, QtGui.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.label_5 = QtGui.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_5)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.margin_top = QtGui.QLineEdit(Form)
        self.margin_top.setObjectName("margin_top")
        self.horizontalLayout.addWidget(self.margin_top)
        self.top_unit = QtGui.QComboBox(Form)
        self.top_unit.setObjectName("top_unit")
        self.horizontalLayout.addWidget(self.top_unit)
        self.formLayout.setLayout(4, QtGui.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_6 = QtGui.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_6)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.margin_bottom = QtGui.QLineEdit(Form)
        self.margin_bottom.setObjectName("margin_bottom")
        self.horizontalLayout_2.addWidget(self.margin_bottom)
        self.bottom_unit = QtGui.QComboBox(Form)
        self.bottom_unit.setObjectName("bottom_unit")
        self.horizontalLayout_2.addWidget(self.bottom_unit)
        self.formLayout.setLayout(5, QtGui.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.label_7 = QtGui.QLabel(Form)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_7)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.margin_left = QtGui.QLineEdit(Form)
        self.margin_left.setObjectName("margin_left")
        self.horizontalLayout_5.addWidget(self.margin_left)
        self.left_unit = QtGui.QComboBox(Form)
        self.left_unit.setObjectName("left_unit")
        self.horizontalLayout_5.addWidget(self.left_unit)
        self.formLayout.setLayout(6, QtGui.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.label_8 = QtGui.QLabel(Form)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_8)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.margin_right = QtGui.QLineEdit(Form)
        self.margin_right.setObjectName("margin_right")
        self.horizontalLayout_6.addWidget(self.margin_right)
        self.right_unit = QtGui.QComboBox(Form)
        self.right_unit.setObjectName("right_unit")
        self.horizontalLayout_6.addWidget(self.right_unit)
        self.formLayout.setLayout(7, QtGui.QFormLayout.FieldRole, self.horizontalLayout_6)
        self.label_9 = QtGui.QLabel(Form)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_9)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.spacing_header = QtGui.QLineEdit(Form)
        self.spacing_header.setObjectName("spacing_header")
        self.horizontalLayout_7.addWidget(self.spacing_header)
        self.header_unit = QtGui.QComboBox(Form)
        self.header_unit.setObjectName("header_unit")
        self.horizontalLayout_7.addWidget(self.header_unit)
        self.formLayout.setLayout(8, QtGui.QFormLayout.FieldRole, self.horizontalLayout_7)
        self.label_10 = QtGui.QLabel(Form)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.label_10)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.spacing_footer = QtGui.QLineEdit(Form)
        self.spacing_footer.setObjectName("spacing_footer")
        self.horizontalLayout_8.addWidget(self.spacing_footer)
        self.footer_unit = QtGui.QComboBox(Form)
        self.footer_unit.setObjectName("footer_unit")
        self.horizontalLayout_8.addWidget(self.footer_unit)
        self.formLayout.setLayout(9, QtGui.QFormLayout.FieldRole, self.horizontalLayout_8)
        self.label_11 = QtGui.QLabel(Form)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(10, QtGui.QFormLayout.LabelRole, self.label_11)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.margin_gutter = QtGui.QLineEdit(Form)
        self.margin_gutter.setObjectName("margin_gutter")
        self.horizontalLayout_9.addWidget(self.margin_gutter)
        self.gutter_unit = QtGui.QComboBox(Form)
        self.gutter_unit.setObjectName("gutter_unit")
        self.horizontalLayout_9.addWidget(self.gutter_unit)
        self.formLayout.setLayout(10, QtGui.QFormLayout.FieldRole, self.horizontalLayout_9)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "First Page Template:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Page Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.size.setItemText(0, QtGui.QApplication.translate("Form", "Custom", None, QtGui.QApplication.UnicodeUTF8))
        self.size.setItemText(1, QtGui.QApplication.translate("Form", "A0", None, QtGui.QApplication.UnicodeUTF8))
        self.size.setItemText(2, QtGui.QApplication.translate("Form", "A1", None, QtGui.QApplication.UnicodeUTF8))
        self.size.setItemText(3, QtGui.QApplication.translate("Form", "A2", None, QtGui.QApplication.UnicodeUTF8))
        self.size.setItemText(4, QtGui.QApplication.translate("Form", "A3", None, QtGui.QApplication.UnicodeUTF8))
        self.size.setItemText(5, QtGui.QApplication.translate("Form", "A4", None, QtGui.QApplication.UnicodeUTF8))
        self.size.setItemText(6, QtGui.QApplication.translate("Form", "A5", None, QtGui.QApplication.UnicodeUTF8))
        self.size.setItemText(7, QtGui.QApplication.translate("Form", "A6", None, QtGui.QApplication.UnicodeUTF8))
        self.size.setItemText(8, QtGui.QApplication.translate("Form", "B0", None, QtGui.QApplication.UnicodeUTF8))
        self.size.setItemText(9, QtGui.QApplication.translate("Form", "B1", None, QtGui.QApplication.UnicodeUTF8))
        self.size.setItemText(10, QtGui.QApplication.translate("Form", "B2", None, QtGui.QApplication.UnicodeUTF8))
        self.size.setItemText(11, QtGui.QApplication.translate("Form", "B3", None, QtGui.QApplication.UnicodeUTF8))
        self.size.setItemText(12, QtGui.QApplication.translate("Form", "B4", None, QtGui.QApplication.UnicodeUTF8))
        self.size.setItemText(13, QtGui.QApplication.translate("Form", "B5", None, QtGui.QApplication.UnicodeUTF8))
        self.size.setItemText(14, QtGui.QApplication.translate("Form", "B6", None, QtGui.QApplication.UnicodeUTF8))
        self.size.setItemText(15, QtGui.QApplication.translate("Form", "letter", None, QtGui.QApplication.UnicodeUTF8))
        self.size.setItemText(16, QtGui.QApplication.translate("Form", "legal", None, QtGui.QApplication.UnicodeUTF8))
        self.size.setItemText(17, QtGui.QApplication.translate("Form", "11\"x17\"", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Height:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "Width:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "Top Margin:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "Bottom Margin:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form", "Left Margin:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Form", "Right Margin:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Form", "Header Margin:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Form", "Footer Margin:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Form", "Gutter Margin:", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Form = QtGui.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

