#!/usr/bin/env python
# -*- coding: utf-8 -*-

#$HeadURL: https://rst2pdf.googlecode.com/svn/trunk/rst2pdf/tests/parselogs.py $
#$LastChangedDate: 2010-03-07 21:25:16 -0600 (Sun, 07 Mar 2010) $
#$LastChangedRevision: 1730 $

# See LICENSE.txt for licensing terms

'''
Parses log files in output directory generated by autotest.py
into stupid HTML output.
'''

from parselogs import getcategories

def dumpinfo():
    mydict = getcategories()
    if not mydict:
        print '\nNo log files found'
    for name, values in sorted(mydict.iteritems()):
        print '<h2>'
        print '\nCategory "%s"\n        (%d tests)\n' % (name, len(values))
        fmt = '%%-%ds  %%s' % max(len(x[0]) for x in values)
        print '</h2>'
        print '<table>'
        href = 'http://code.google.com/p/rst2pdf/issues/detail?id='
        for testname, checksum in sorted(values):

            print '<tr>'
            print '<td>'
            if testname.startswith('test_issue_'):
                testnum = testname.split('_')[2]
                print '<a href="%s%s">%s</a>' % (href, testnum, testname)
            else:
                print testname
            print '</td>'
            print '<td>'
            print '<a href="output/%s.pdf">%s</a>' % (testname, checksum)
            print '</td>'
            print '</tr>'
        print '</table>'
    print

if __name__ == '__main__':
    print '<html><body>'
    dumpinfo()
    print '<pre>'
    print '\n\n'.join(10*'.')  # A bit of separation from end for scrolling...
    print '</pre>'
    print '</body></html>'
